# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ubuntu/ward_method

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ubuntu/ward_method

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/ward_method/CMakeFiles /home/ubuntu/ward_method/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ubuntu/ward_method/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named wards.exe

# Build rule for target.
wards.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wards.exe
.PHONY : wards.exe

# fast build rule for target.
wards.exe/fast:
	$(MAKE) -f CMakeFiles/wards.exe.dir/build.make CMakeFiles/wards.exe.dir/build
.PHONY : wards.exe/fast

cpp/hierarchical_clustering.o: cpp/hierarchical_clustering.cc.o

.PHONY : cpp/hierarchical_clustering.o

# target to build an object file
cpp/hierarchical_clustering.cc.o:
	$(MAKE) -f CMakeFiles/wards.exe.dir/build.make CMakeFiles/wards.exe.dir/cpp/hierarchical_clustering.cc.o
.PHONY : cpp/hierarchical_clustering.cc.o

cpp/hierarchical_clustering.i: cpp/hierarchical_clustering.cc.i

.PHONY : cpp/hierarchical_clustering.i

# target to preprocess a source file
cpp/hierarchical_clustering.cc.i:
	$(MAKE) -f CMakeFiles/wards.exe.dir/build.make CMakeFiles/wards.exe.dir/cpp/hierarchical_clustering.cc.i
.PHONY : cpp/hierarchical_clustering.cc.i

cpp/hierarchical_clustering.s: cpp/hierarchical_clustering.cc.s

.PHONY : cpp/hierarchical_clustering.s

# target to generate assembly for a file
cpp/hierarchical_clustering.cc.s:
	$(MAKE) -f CMakeFiles/wards.exe.dir/build.make CMakeFiles/wards.exe.dir/cpp/hierarchical_clustering.cc.s
.PHONY : cpp/hierarchical_clustering.cc.s

cpp/main.o: cpp/main.cc.o

.PHONY : cpp/main.o

# target to build an object file
cpp/main.cc.o:
	$(MAKE) -f CMakeFiles/wards.exe.dir/build.make CMakeFiles/wards.exe.dir/cpp/main.cc.o
.PHONY : cpp/main.cc.o

cpp/main.i: cpp/main.cc.i

.PHONY : cpp/main.i

# target to preprocess a source file
cpp/main.cc.i:
	$(MAKE) -f CMakeFiles/wards.exe.dir/build.make CMakeFiles/wards.exe.dir/cpp/main.cc.i
.PHONY : cpp/main.cc.i

cpp/main.s: cpp/main.cc.s

.PHONY : cpp/main.s

# target to generate assembly for a file
cpp/main.cc.s:
	$(MAKE) -f CMakeFiles/wards.exe.dir/build.make CMakeFiles/wards.exe.dir/cpp/main.cc.s
.PHONY : cpp/main.cc.s

cpp/nn_cluster.o: cpp/nn_cluster.cc.o

.PHONY : cpp/nn_cluster.o

# target to build an object file
cpp/nn_cluster.cc.o:
	$(MAKE) -f CMakeFiles/wards.exe.dir/build.make CMakeFiles/wards.exe.dir/cpp/nn_cluster.cc.o
.PHONY : cpp/nn_cluster.cc.o

cpp/nn_cluster.i: cpp/nn_cluster.cc.i

.PHONY : cpp/nn_cluster.i

# target to preprocess a source file
cpp/nn_cluster.cc.i:
	$(MAKE) -f CMakeFiles/wards.exe.dir/build.make CMakeFiles/wards.exe.dir/cpp/nn_cluster.cc.i
.PHONY : cpp/nn_cluster.cc.i

cpp/nn_cluster.s: cpp/nn_cluster.cc.s

.PHONY : cpp/nn_cluster.s

# target to generate assembly for a file
cpp/nn_cluster.cc.s:
	$(MAKE) -f CMakeFiles/wards.exe.dir/build.make CMakeFiles/wards.exe.dir/cpp/nn_cluster.cc.s
.PHONY : cpp/nn_cluster.cc.s

cpp/ward.o: cpp/ward.cc.o

.PHONY : cpp/ward.o

# target to build an object file
cpp/ward.cc.o:
	$(MAKE) -f CMakeFiles/wards.exe.dir/build.make CMakeFiles/wards.exe.dir/cpp/ward.cc.o
.PHONY : cpp/ward.cc.o

cpp/ward.i: cpp/ward.cc.i

.PHONY : cpp/ward.i

# target to preprocess a source file
cpp/ward.cc.i:
	$(MAKE) -f CMakeFiles/wards.exe.dir/build.make CMakeFiles/wards.exe.dir/cpp/ward.cc.i
.PHONY : cpp/ward.cc.i

cpp/ward.s: cpp/ward.cc.s

.PHONY : cpp/ward.s

# target to generate assembly for a file
cpp/ward.cc.s:
	$(MAKE) -f CMakeFiles/wards.exe.dir/build.make CMakeFiles/wards.exe.dir/cpp/ward.cc.s
.PHONY : cpp/ward.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... wards.exe"
	@echo "... edit_cache"
	@echo "... cpp/hierarchical_clustering.o"
	@echo "... cpp/hierarchical_clustering.i"
	@echo "... cpp/hierarchical_clustering.s"
	@echo "... cpp/main.o"
	@echo "... cpp/main.i"
	@echo "... cpp/main.s"
	@echo "... cpp/nn_cluster.o"
	@echo "... cpp/nn_cluster.i"
	@echo "... cpp/nn_cluster.s"
	@echo "... cpp/ward.o"
	@echo "... cpp/ward.i"
	@echo "... cpp/ward.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

